name: Alist Batch Add Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar git
    - name: Download and extract Alist
      run: |
        wget https://github.com/alist-org/alist/releases/download/v3.26.0/alist-linux-amd64.tar.gz
        tar -zxvf alist-linux-amd64.tar.gz
        chmod +x alist
    - name: Clone alist_batch_add repository
      run: git clone https://github.com/yzbtdiy/alist_batch_add.git
    - name: Set new password for Alist admin
      run: ./alist admin set NEW_PASSWORD
    - name: Run Python script
      run: |
        cd alist_batch_add
        python mai.py






















